services:
  
  app:
    image: 'news'
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/news_db

  db:
    image: 'postgres:14'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=12345'
      - 'POSTGRES_DB=news_db'